name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      event-type:
        description: 'Type of Terraform operation'
        required: true
        default: 'destroy' # Default value, change as needed

jobs: 
  destroy:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Clone Repo LAB06
        run: |
            git clone https://github.com/suatceyhan/Lab06.git

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Blob Release
        run: |
            az storage blob lease break \
              --account-name suatterraformstate \
              --container-name terrasuatcontainer \
              --blob-name terraform.tfstate

      - name: Terraform Destroy
        run: |
            cd /home/runner/work/Lab06/Lab06/Lab06
            chmod +x ./scripts/destroy.sh
            ./scripts/destroy.sh

      - name: Blob Lease
        run: |
            az storage blob lease acquire \
              --account-name suatterraformstate \
              --container-name terrasuatcontainer \
              --blob-name terraform.tfstate  