name: Terraform Plan

on:
  push:
    branches:
      - master

jobs: 
  plan:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: 'Run az commands'
        run: |
            az account show
            az group list          

      - name: Clone Repo LAB06
        run: |
            git clone https://github.com/suatceyhan/Lab06.git

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: |
            cd /home/runner/work/Lab06/Lab06/Lab06
            chmod +x ./scripts/init.sh
            ./scripts/init.sh

      - name: Terraform Plan
        run: |
            cd /home/runner/work/Lab06/Lab06/Lab06
            chmod +x ./scripts/plan.sh
            ./scripts/plan.sh
