name: Terraform Deploy

on:
  push:
    branches:
      - master  # Adjust this to match your branch

permissions:
  id-token: write
  contents: read

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
          
    #   - name: Azure CLI script
    #     uses: azure/CLI@v1
    #     with:
    #       azcliversion: latest
    #       inlineScript: |
    #         az account show

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: ./scripts/init.sh

      - name: Terraform Plan
        run: ./scripts/plan.sh

      - name: Terraform Apply
        run: ./scripts/apply.sh
